### ISSUE TITLE
NEAR BALANCE ERROR

### ISSUE THREAD

**Issue by badmosh23** [Zlkcyber/hotWallet#1]
![Screenshot (258)](https://github.com/Zlkcyber/hotWallet/assets/150448156/4ccf16a0-c446-417d-a846-e26abab087a3)
ITS JUST KEEP SHOWING THIS ERROR
I HAVE SOME NEAR IN MY WALLET BUT STILL

**Comment by Zlkcyber** [comment]
@badmosh23 make sure change account-temp.js to account.js

**Comment by badmosh23** [comment]
Did but same error

**Comment by Zlkcyber** [comment]
@badmosh23 do the wallet you put already registered on hot wallet on telegram?

**Comment by badmosh23** [comment]
Yes

**Comment by badmosh23** [comment]
I should try other bots

**Comment by Zlkcyber** [comment]
@badmosh23 okay good luck
