### ISSUE TITLE
Error "NearBalanceUser"

### ISSUE THREAD

**Issue by VanyaOnegin** [Zlkcyber/hotWallet#3]
I used this software for about a month and everything was fine, but the other day I started getting this error, I don’t understand what the problem is, I updated Node JS and manually downloaded all the libraries.

![Error](https://github.com/user-attachments/assets/a899fbf5-0f12-466c-89ea-9a6069fe4e4a)

**Comment by Zlkcyber** [comment]
@VanyaOnegin fixed
