### ISSUE TITLE
New Error 

### ISSUE THREAD

**Issue by VanyaOnegin** [Zlkcyber/hotWallet#4]
Thank you for correcting the previous error, there is no longer an error with NearWalletBalance, but now a new one has appeared, can you please fix it if it’s not difficult for you?

![Error2](https://github.com/user-attachments/assets/1cc538bc-87e0-4592-9d6d-4db24c04c162)

**Comment by Zlkcyber** [comment]
@VanyaOnegin oke got it the problem is in the smart contract

**Comment by VanyaOnegin** [comment]
Is the problem on my side?

**Comment by Zlkcyber** [comment]
@VanyaOnegin no, the problem on script
i will try to fix later if i have time

**Comment by VanyaOnegin** [comment]
Bro, you help so much, can I please send you a little Near, send me your Near adress

**Comment by Zlkcyber** [comment]
@VanyaOnegin near rpc is down right now bro,

**Comment by Zlkcyber** [comment]
@VanyaOnegin i will put my address later if the script already work back, thanks

**Comment by Ziko225** [comment]
> @VanyaOnegin near rpc is down right now bro, 

Are you sure about that?

https://nearblocks.io/txns/9oQXaJTrV9eKkr8PD69rCbaCgc7QPbwSZAiw64z6HJep

**Comment by Zlkcyber** [comment]
@Ziko225 yes bro already try changing rpc and the script is work fine

**Comment by Zlkcyber** [comment]
@Ziko225 @VanyaOnegin i will update the script soon

**Comment by Ziko225** [comment]
> @Ziko225 yes bro already try changing rpc and the script is work fine
Nice! Can you tell me what RPC do you use? 
Ex: 
```
export const mainnetConfig = {
  networkId: "mainnet",
  nodeUrl: 'https://rpc.mainnet.near.org',  // this is rpc for near mainnet
  walletUrl: "https://wallet.mainnet.near.org",
  helperUrl: "https://helper.mainnet.near.org",
};
```

**Comment by Zlkcyber** [comment]
@VanyaOnegin @VanyaOnegin already updated, enjoy

**Comment by VasiliyEvilopov** [comment]
Yeh bro, thanks, it works, I mean can you send your NEAR Adress like that: 
![Error](https://github.com/user-attachments/assets/6d7830f4-3693-4668-8b2e-1c7311340148)

**Comment by VanyaOnegin** [comment]
Or can you send your TON Adress

**Comment by Zlkcyber** [comment]
@VanyaOnegin zlkcyber.tg/zlkcyber.near thanks before

**Comment by VasiliyEvilopov** [comment]
Thanks, I send 1 Near, you can check your balance
